In [36]:
import pandas as pd

##Part 3

shoppers = {
'Paula':{'Is':4,'Juice':2,'Kakao':3,'Lagkager':2},
'Peter':{'Is':2,'Juice':5,'Kakao':0, 'Lagkager':4},
'Pandora':{'Is':5,'Juice':3, 'Kakao':4, 'Lagkager':5},
'Pietro':{'Is':1,'Juice':8, 'Kakao':9, 'Lagkager':1}
}
shop_prices = {
'Netto': {'Is':10.50,'Juice':2.25,'Kakao':4.50,'Lagkager':33.50},
'Fakta': {'Is':4.00,'Juice':4.50,'Kakao':6.25,'Lagkager':20.00}
}

shopper_df = pd.DataFrame(shoppers).T
prices_df = pd.DataFrame(shop_prices)

shopper_df.to_numpy()
prices_df.to_numpy()

result = shopper_df.dot(prices_df)

print(result)

          Paula  Peter  Pandora  Pietro
Is            4      2        5       1
Juice         2      5        3       8
Kakao         3      0        4       9
Lagkager      2      4        5       1


In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

#1. Feature space from csv file. Read `data/ds_salaries.csv` into a pandas dataframe
raw_df = pd.read_csv("data/ds_salaries.csv")

#2. Prune the dataset to only have columns: "work_year", "experience_level", "salary_in_usd", "job_title", "company_location", "company_size".
df = raw_df[['work_year', 'experience_level', 'salary_in_usd', 'job_title', 'company_location', 'company_size']]

#3. Onehot encode "experience_level". Hint: look up pandas: `get_dummies()` method.
OneHotencoder = OneHotEncoder()
data_encoded = OneHotencoder.fit_transform(df[['experience_level']])
print(data_encoded.todense())

#4. labelencode "company_location"
labelEncoder = LabelEncoder()
data = labelEncoder.fit_transform(df[['company_location']])
print(data)

#5. Normalize the company_location number (relative value between 0-1) ![](https://cdn-images-1.medium.com/max/253/1*Dl3P3Rrzto258X0Ales9Xw.png)
for n in data:
    print((n-data.min()) / (data.max() - data.min()))

#6. Make binning of the salary column (both cut and qcut methods).





[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
[12 29 18 20 48 48 48 22 48 38 17 25 17 48 48 39 29 18 25 48  9 25 19 48
  0 48 37 34 48  6 12 48 48 48 17  2 48 48 36 48 48 16 41 48 18 12 18 48
 48 17 25 48 13 12 48 12 16 48 48 48 48 48 28 48 21 12 12 48 48  2 31 17
 18 48 48 17 48 25 48 48 12 48  6 16 40 40 17 48 48 48 13 12 25 48 25 44
 48 48 48 48 48 48 48 48 48 18  6 48 48 25 12 18 18 48 37 48 36 19 48 48
 42 48 48 18 16 48 48 25 25 25 26 17 48  5 48 48 29 29 48 48 48 48 48 48
 48  4 17 48 48 48 29 48  6 47 48  6 24 48 48 48 43 43 33 12 12 48 48 48
 48 48 48 18 48 48 41 48 34  8 48 48 25 12 48 18 39 27 18 16 18 29 17 10
 32 48  6 48 30 25 48 48  2 48 16 48 48  5 48 48 48 48 45 17 18  7 12 48
 13 12  4 48 40 18 25 18  6 48  6 12 48  6 25 48 48 48 48 48  6 16 49 25
  6 48 48 48  1 18 17 46 18 48 48 48 48 25 48  6 48 12 48 12 48 12 25 25
 12 48 48 48 46 12 48  5 12 12 17 48 48 16 46 31 48  9 37 48 11 25 45 48
 28 48 48 48 48 48 48 48 48 

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
